apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
  namespace: cosmos
spec:
  template:
    spec:
      containers:
      - name: validator
        resources:
          requests:
            memory: "4Gi"
            cpu: "3"
          limits:
            memory: "4Gi"
            cpu: "3"
